on:
  workflow_dispatch:
    inputs:
      app_blob:
        type: string
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repositories
        run: |
          ls -la
          echo '${{ inputs.app_blob }}'
          git clone https://github.com/uet-app-distributor/template-generator.git
          cd template-generator
          ls -la
      - name: Generate files
        run: |
          ls -la
          cd template-generator
          ls -la
#         pip install -r requirement.txt
#         python3 main.py sample-app-config.yaml
#         cat sample*
