run-name: Provision Platform Infrastructure

on:
  workflow_dispatch:

permissions:
  issues: write

env:
  DEFAULT_ORG: uet-app-distributor
  DEFAULT_REVIEWER: thai-nm
  GOOGLE_REGION: asia-southeast1
  GOOGLE_ZONE: asia-southeast1-a
  GOOGLE_PROJECT: uet-app-distributor
  TERRAFORM_LIVE_REPO: terraform-live-repo
  TERRAFORM_REMOTE_STATE_REPO: terraform-live-repo-remote-state

jobs:
  decommision-platform-infrastructure:
    name: Decommission platform infrastructure
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout terraform-live-repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DEFAULT_ORG }}/${{ env.TERRAFORM_LIVE_REPO }}
          ref: develop

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GOOGLE_RUNNER_CREDENTIALS }}

      - name: Terraform Plan Destroy - Platform infrastructure
        run: |
          terraform init
          terraform validate
          terraform plan -destroy

      - name: Require approvals
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.RUNNER_ACCESS_TOKEN }}
          approvers: ${{ env.DEFAULT_REVIEWER }}
          minimum-approvals: 1
          timeout-minutes: 10
          issue-title: "Require approvals"
          issue-body: "Decommision platform infrastructure requires reviewers."

      - name: Terraform Apply - Platform infrastructure
        run: terraform destroy -auto-approve

  remove-remote-backend-bucket:
    name: Remove remote backend bucket
    needs: decommision-platform-infrastructure
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout terraform-live-repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DEFAULT_ORG }}/${{ env.TERRAFORM_REMOTE_STATE_REPO }}
          ref: develop

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GOOGLE_RUNNER_CREDENTIALS }}

      - name: Terraform Plan Destroy - Remote backend bucket
        run: |
          terraform init
          terraform validate
          terraform plan -destroy

      - name: Require approvals
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.RUNNER_ACCESS_TOKEN }}
          approvers: ${{ env.DEFAULT_REVIEWER }}
          minimum-approvals: 1
          timeout-minutes: 10
          issue-title: "Require approvals"
          issue-body: "Initialize remote state backend bucket requires reviewers."

      - name: Terraform Destroy - Remote backend bucket
        run: terraform destroy -auto-approve
