name: Deploy App Distributor
run-name: Deploy App Distributor

on:
  workflow_dispatch:

env:
  DISTRIBUTOR_MANIFEST_PREFIX: https://raw.githubusercontent.com/uet-app-distributor/platform-app-distributor/main

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo platform-app-distributor
        uses: actions/checkout@v3
        with:
          repository: uet-app-distributor/platform-app-distributor
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/uet-app-distributor:latest

  deploy:
    name: Deploy App Distributor
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DISTRIBUTOR_INSTANCE_HOST }}
          port: ${{ secrets.DISTRIBUTOR_INSTANCE_SSH_PORT }}
          key: ${{ secrets.DISTRIBUTOR_INSTANCE_SSH_KEY }}
          username: ${{ secrets.DISTRIBUTOR_INSTANCE_PRIMARY_USER }}
          script: |
            microk8s kubectl apply -f ${{ env.DISTRIBUTOR_MANIFEST_PREFIX }}/deployment.yaml
            microk8s kubectl rollout restart deployment -n uet-app-distributor distributor
