name: Deploy Appsmith
run-name: Deploy Appsmith

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout platform-general-tools repository
        uses: actions/checkout@v3
        with:
          repository: uet-app-distributor/platform-general-tools
          ref: main
          path: tools

      - name: Send values.yaml file to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DISTRIBUTOR_INSTANCE_HOST }}
          port: ${{ secrets.DISTRIBUTOR_INSTANCE_SSH_PORT }}
          key: ${{ secrets.DISTRIBUTOR_INSTANCE_SSH_KEY }}
          username: ${{ secrets.DISTRIBUTOR_INSTANCE_PRIMARY_USER }}
          source: "tools/manifests/appsmith/values.yaml"
          target: /tmp/appsmith
          strip_components: 3

      - name: Deploy Appsmith
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DISTRIBUTOR_INSTANCE_HOST }}
          port: ${{ secrets.DISTRIBUTOR_INSTANCE_SSH_PORT }}
          key: ${{ secrets.DISTRIBUTOR_INSTANCE_SSH_KEY }}
          username: ${{ secrets.DISTRIBUTOR_INSTANCE_PRIMARY_USER }}
          script: |
            microk8s helm repo add appsmith https://helm.appsmith.com
            microk8s helm repo update
            microk8s helm upgrade -f /tmp/appsmith/values.yaml
                                  --install appsmith appsmith/appsmith \
                                  --create-namespace \
                                  --namespace appsmith\
                                  
