name: Deploy cluster secrets
run-name: Deploy cluster secrets

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy secret manifests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo containing secrets
        uses: actions/checkout@v3
        with:
          repository: uet-app-distributor/secrets
          ref: main
          token: ${{ secrets.GENERAL_GITHUB_ACCESS_TOKEN }}

      - name: Send secret manifest files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DISTRIBUTOR_INSTANCE_HOST }}
          port: ${{ secrets.DISTRIBUTOR_INSTANCE_SSH_PORT }}
          key: ${{ secrets.DISTRIBUTOR_INSTANCE_SSH_KEY }}
          username: ${{ secrets.DISTRIBUTOR_INSTANCE_PRIMARY_USER }}
          source: "secret_manifests/*.yaml"
          target: /tmp/secrets

      - name: Deploy secrets
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DISTRIBUTOR_INSTANCE_HOST }}
          port: ${{ secrets.DISTRIBUTOR_INSTANCE_SSH_PORT }}
          key: ${{ secrets.DISTRIBUTOR_INSTANCE_SSH_KEY }}
          username: ${{ secrets.DISTRIBUTOR_INSTANCE_PRIMARY_USER }}
          script: |
            microk8s kubectl apply -f /tmp/secrets/secret_manifests
