run-name: Deploy Customer Applications

on:
  workflow_dispatch:
    inputs:
      app_blob:
        description: "App configurations as a blob object on GCS."
        type: string
        required: true
      github_user:
        description: "GitHub user."
        type: string
        required: true
      github_repo:
        description: "GitHub repo."
        type: string
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout template-generator repository
        uses: actions/checkout@v3
        with:
          repository: uet-app-distributor/template-generator
          ref: main
          path: template-generator

      - name: List files
        run: |
          ls -la
          pwd

      - name: Checkout customer application repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.github_user }}/${{ inputs.github_repo }}
          ref: main
          path: customer-app

      - name: List files
        run: |
          ls -la
          ls -la ${{ github.workspace }}
          pwd
