name: Deploy Distributor
run-name: Deploy Distributor

on:
  workflow_dispatch:

env:
  DISTRIBUTOR_MANIFEST_PREFIX: https://raw.githubusercontent.com/uet-app-distributor/platform-app-distributor/main

jobs:
  deploy:
    name: Deploy App Distributor
    runs-on: ubuntu-22.04
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DISTRIBUTOR_INSTANCE_HOST }}
          port: ${{ secrets.DISTRIBUTOR_INSTANCE_SSH_PORT }}
          key: ${{ secrets.DISTRIBUTOR_INSTANCE_SSH_KEY }}
          username: ${{ secrets.DISTRIBUTOR_INSTANCE_PRIMARY_USER }}
          script: |
            microk8s kubectl apply -f ${{ env.DISTRIBUTOR_MANIFEST_PREFIX }}/deployment.yaml
            microk8s kubectl rollout restart deployment -n uet-app-distributor distributor
