run-name: Deploy App Distributor

on:
  workflow_dispatch:
    inputs:
      distributor_version:
        type: choice
        description: Version of distributor to deploy
        options: 
        - main
        - develop

permissions:
  issues: write

env:
  DEFAULT_ORG: uet-app-distributor
  DISTRIBUTOR_REPO: platform-app-distributor

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo platform-app-distributor
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DEFAULT_ORG }}/${{ env.TERRAFORM_LIVE_REPO }}
          ref: ${{ inputs.distributor_version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/app:latest
  deploy:
    name: Deploy 
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy Distributor
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            kubectl apply -f deployment.yaml
