name: Initialize remote backend
run-name: Initialize remote backend

on:
  workflow_dispatch:

env:
  DEFAULT_ORG: uet-app-distributor
  DEFAULT_REVIEWER: thai-nm
  GOOGLE_REGION: asia-southeast1
  GOOGLE_ZONE: asia-southeast1-a
  GOOGLE_PROJECT: uet-app-distributor
  TERRAFORM_REMOTE_STATE_REPO: terraform-live-repo-remote-state

jobs:
  deploy-remote-backend-bucket:
    permissions:
      issues: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout terraform-live-repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DEFAULT_ORG }}/${{ env.TERRAFORM_REMOTE_STATE_REPO }}
          ref: develop

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GOOGLE_RUNNER_CREDENTIALS }}

      - name: Terraform Plan - Remote backend bucket
        run: |
          terraform init
          terraform validate
          terraform plan

      - name: Require approvals
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.RUNNER_ACCESS_TOKEN }}
          approvers: ${{ env.DEFAULT_REVIEWER }}
          minimum-approvals: 1
          timeout-minutes: 10
          issue-title: "Require approvals"
          issue-body: "Initialize remote state backend bucket requires reviewers."

      - name: Terraform Apply - Remote backend bucket
        run: terraform apply -auto-approve
