run-name: Provision Platform Infrastructure

on:
  workflow_dispatch:
    inputs:
      platform_version:
        type: choice
        description: Version of platform to deploy
        options: 
        - main
        - develop

env:
  DEFAULT_ORG: uet-app-distributor
  DEFAULT_REVIEWER: thai-nm
  GOOGLE_REGION: asia-southeast1
  GOOGLE_ZONE: asia-southeast1-a
  GOOGLE_PROJECT: uet-app-distributor
  TERRAFORM_LIVE_REPO: terraform-live-repo

jobs:
  provision-platform-infrastructure:
    name: Provision platform infrastructure
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout terraform-live-repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DEFAULT_ORG }}/${{ env.TERRAFORM_LIVE_REPO }}
          ref: ${{ inputs.platform_version }}

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GOOGLE_RUNNER_CREDENTIALS }}

      - name: Terraform Plan - Platform infrastructure
        run: |
          terraform init
          terraform validate
          terraform plan

      - name: Require approvals
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.RUNNER_ACCESS_TOKEN }}
          approvers: ${{ env.DEFAULT_REVIEWER }}
          minimum-approvals: 1
          timeout-minutes: 10
          issue-title: "Require approvals"
          issue-body: "Provision platform infrastructure requires reviewers."

      - name: Terraform Apply - Platform infrastructure
        run: terraform apply -auto-approve
